name: Auto Tag Push
on:
  pull_request:
    branches:
      - test
    types:
        - closed
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && ( startsWith(github.event.pull_request.head.ref, 'test/') )
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: git fetch origin ${{ github.event.pull_request.head.ref }}
      - run: git checkout ${{ github.event.pull_request.head.ref }}
      - run: git tag -a `echo '${{ github.event.pull_request.head.ref }}' | sed -e 's/test\///'  -m "${{ github.event.pull_request.title }}"
      - run: git push origin `echo '${{ github.event.pull_request.head.ref }}' | sed -e 's/test\///'
