name: App Deploy

on:
  workflow_dispatch:

jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.TEST }}"
      - name: Echo a secret  
        run: echo "your secret token is ${{ secrets.TEST }}"


        
