name: App Deploy

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        required: true
        description: デプロイ先の環境
        options:
          - "evaluation"
          - "staging"
      branch:
        required: true
        description: デプロイ対象のブランチ
        default: development

permissions:
  id-token: write 
  contents: read 

jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: test
        id: test
        uses: ./.github/actions/test






        
