name: App Deploy2

on:
  workflow_dispatch:

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
        with:
          service-names: '3.9.1'

